parse_config:
  mark_alternate_layer_activators: true
  sticky_label: $$mdi:gesture-tap-hold$$
  trans_legend:
    type: trans

  raw_binding_map:
    "&none":
      type: none

    # Macro
    "&wintb":
      tap: $$mdi:dock-window$$
    "&winpv":
      hold: $$mdi:arrow-left-bold$$
      tap: $$mdi:dock-window$$
    "&winnx":
      hold: $$mdi:arrow-right-bold$$
      tap: $$mdi:dock-window$$
    "&tabnx":
      tap: $$mdi:window-restore$$
    "&ppy_dpi":
      tap: $$mdi:mouse$$
      hold: DPI
    "&ppy_scr":
      tap: $$mdi:mouse-move-vertical$$
      hold: Scroll
    "&wordpv":
      hold: $$mdi:arrow-left-bold$$
      tap: Word
    "&wordnx":
      hold: $$mdi:arrow-right-bold$$
      tap: Word

    # Mouse
    "&mkp LCLK":
      tap: $$mdi:mouse$$
      hold: L
    "&mkp RCLK":
      tap: $$mdi:mouse$$
      hold: R
    "&mkp MCLK":
      tap: $$mdi:mouse$$
      hold: M
    "&mkp MB4":
      tap: $$mdi:mouse$$
      hold: 1
    "&mkp MB5":
      tap: $$mdi:mouse$$
      hold: 2

  # ZMK
  zmk_keycode_map:
    # Symbols
    EXCL: "!"
    AT: "@"
    HASH: "#"
    DLLR: "$"
    PRCNT: "%"
    CARET: "^"
    AMPS: "&"
    STAR: "*"
    LPAR: "("
    RPAR: ")"
    EQUAL: "="
    PLUS: "+"
    MINUS: "-"
    UNDER: "_"
    FSLH: "/"
    QMARK: "?"
    BSLH: "\\"
    PIPE: "|"
    SEMI: ";"
    COLON: ":"
    APOS:
      tap: "'"
      shifted: "\""
    LT: "<"
    DOT: "."
    COMMA: ","
    GT: ">"
    LBKT: "["
    LBRC: "{"
    RBKT: "]"
    RBRC: "}"
    GRAVE: "`"
    TILDE: "~"

    # Numbers
    N1:
      tap: 1
    N2:
      tap: 2
    N3:
      tap: 3
    N4:
      tap: 4
    N5:
      tap: 5
    N6:
      tap: 6
    N7:
      tap: 7
    N8:
      tap: 8
    N9:
      tap: 9
    N0:
      tap: 0

    # Modifiers
    LCTRL: $$mdi:apple-keyboard-control$$
    LALT: $$mdi:apple-keyboard-option$$
    LSHIFT: $$mdi:apple-keyboard-shift$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    LCMD: $$mdi:apple-keyboard-command$$

    # Navi
    UP: $$mdi:arrow-up-bold$$
    DOWN: $$mdi:arrow-down-bold$$
    LEFT: $$mdi:arrow-left-bold$$
    RIGHT: $$mdi:arrow-right-bold$$
    HOME: ‚á±
    END: ‚á≤
    PG_DN: ‚áü
    PG_UP: ‚áû

    # Whitespace
    RET: $$mdi:keyboard-return$$
    ESC: $$mdi:keyboard-esc$$
    TAB: $$mdi:keyboard-tab$$
    SPACE: $$mdi:keyboard-space$$
    BSPC: $$mdi:backspace-outline$$
    DEL: $$mdi:backspace-reverse-outline$$

    # Sound
    C_MUTE: $$mdi:volume-off$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-low$$

    # Bluetooth
    BT_CLR: $$mdi:bluetooth-off$$
    BT_SEL: $$mdi:bluetooth-connect$$

    # ETC
    CAPS: $$mdi:apple-keyboard-caps$$
    LANG1: "Ìïú/ÏòÅ"
    PSCRN: "Print Screen"
    SCROLLLOCK: "Scroll Lock"
    PAUSE_BREAK: "Pause Break"

  zmk_combos:
    combo_minus:
      layers: [BASE]
    combo_plus:
      layers: [BASE]
    combo_equal:
      offset: 0.8
      align: top
      layers: [BASE]
    combo_tab:
      layers: [BASE]
      key:
        tap: $$mdi:keyboard-tab$$
    combo_bspc:
      layers: [BASE]
      key:
        tap: $$mdi:backspace-outline$$
    combo_esc:
      layers: [BASE]
      key:
        tap: $$mdi:keyboard-esc$$
    combo_bslh:
      layers: [BASE]
    combo_at:
      layers: [BASE]
    combo_grave:
      align: bottom
      layers: [BASE]
    combo_lpar:
      layers: [BASE]
    combo_rpar:
      layers: [BASE]
    combo_pipe:
      offset: 0.8
      align: top
      layers: [BASE]
    combo_lang:
      layers: [BASE]
      key:
        tap: "Ìïú/ÏòÅ"
    combo_caps:
      layers: [BASE]
      key:
        tap: $$mdi:apple-keyboard-caps$$
    combo_lbkt:
      layers: [BASE]
    combo_rbkt:
      layers: [BASE]
    combo_tilde:
      align: bottom
      layers: [BASE]
    combo_mclk:
      align: bottom
      layers: [BASE]

draw_config:
  # key dimensions, non-ortho layouts use key_h for width as well
  # key_w: 100 # This doesn't seem to do anything? ü§î
  key_h: 60

  # keys border radius
  key_rx: 4
  key_ry: 4

  # key labels line spacing for multi-line labels
  line_spacing: 1

  # combo box dimensions
  combo_w: 30
  combo_h: 40

  # padding from the edge of cap to top and bottom legends
  small_pad: 4

  # Padding between keys
  inner_pad_w: 1.5
  inner_pad_h: 1.5

  # padding between layers
  outer_pad_w: 0
  outer_pad_h: 0

  # gap between two halves for ortho layout generator
  # split_gap: 20 # This doesn't seem to have any effect either? ü§î

  # as it reads on the tin can, this comment is here for consistency
  append_colon_to_layer_header: false

  # shrink font size for legends wider than this many chars, set to 0 to disable
  # ideal value depends on the font size defined in svg_style and width of the boxes
  shrink_wide_legends: 5

  # Glyphs dimensions
  glyph_tap_size: 18
  glyph_hold_size: 14
  glyph_shifted_size: 14

  # Custom CSS
  svg_style: |
    /* inherit to force styles through use tags */
    svg path {
        fill: inherit;
    }

    /* font and background color specifications */
    svg.keymap {
        /*
         * ====================
         * Theme Variables
         * ====================
         */

        --logo-path: none;
        --logo-size: 12%;
        --logo-position: 49.5% 5%;

        /* === Colors === */

        --color--material--blue--50: rgb(227, 242, 253);
        --color--material--blue--100: rgb(187, 222, 251);
        --color--material--blue--200: rgb(144, 202, 249);
        --color--material--blue--300: rgb(100, 181, 246);
        --color--material--blue--400: rgb(66, 165, 245);
        --color--material--blue--500: rgb(33, 150, 243);
        --color--material--blue--600: rgb(30, 136, 229);
        --color--material--blue--700: rgb(25, 118, 210);
        --color--material--blue--800: rgb(21, 101, 192);
        --color--material--blue--900: rgb(13, 71, 161);
        --color--material--blue--a100: rgb(130, 177, 255);
        --color--material--blue--a200: rgb(68, 138, 255);
        --color--material--blue--a400: rgb(41, 121, 255);
        --color--material--blue--a700: rgb(41, 98, 255);

        --color--material--blue-gray--50: rgb(236, 239, 241);
        --color--material--blue-gray--100: rgb(207, 216, 220);
        --color--material--blue-gray--200: rgb(176, 190, 197);
        --color--material--blue-gray--300: rgb(144, 164, 174);
        --color--material--blue-gray--400: rgb(120, 144, 156);
        --color--material--blue-gray--500: rgb(96, 125, 139);
        --color--material--blue-gray--600: rgb(84, 110, 122);
        --color--material--blue-gray--700: rgb(69, 90, 100);
        --color--material--blue-gray--800: rgb(55, 71, 79);
        --color--material--blue-gray--900: rgb(38, 50, 56);

        --color--bg: transparent;
        --color--text: var(--color--material--blue-gray--900);

        --color--layer--text: var(--color--material--blue-gray--400);

        --color--key--bg: var(--color--material--blue-gray--50);
        --color--key--border: white;
        --color--key--text--tap: var(--color--text);
        --color--key--text--shifted: var(--color--material--blue-gray--500);
        --color--key--text--hold: var(--color--material--blue-gray--500);

        --color--combo--bg: var(--color--material--blue--50);
        --color--combo--border: var(--color--material--blue--300);
        --color--combo--dendron: var(--color--combo--border);
        --color--combo--text--tap: var(--color--material--blue-gray--800);
        --color--combo--text--shifted: var(--color--material--blue-gray--400);
        --color--combo--text--hold: var(--color--combo--text--tap);

        --color--trans--bg: transparent;
        --color--trans--border: var(--color--material--blue-gray--400);
        --color--trans--text--tap: var(--color--trans--border);
        --color--trans--text--shifted: var(--color--trans--text--tap);
        --color--trans--text--hold: var(--color--trans--text--tap);

        --color--ghost--bg: var(--color--trans--bg);
        --color--ghost--border: var(--color--trans--border);
        --color--ghost--text--tap: var(--color--trans--text--tap);
        --color--ghost--text--shifted: var(--color--trans--text--shifted);
        --color--ghost--text--hold: var(--color--trans--text--shifted);

        /*
         * ====================
         * /End Theme Variables
         * ====================
         */

        font-family: SFMono-Regular,Consolas,Liberation Mono,Menlo,monospace;
        font-size: 16px;
        font-kerning: normal;
        text-rendering: optimizeLegibility;
        fill: var(--color--text);
        background-color: var(--color--bg);
        background-image: var(--logo-path);
        background-repeat: no-repeat;
        background-position: var(--logo-position);
        background-size: var(--logo-size) auto;
    }

    rect,
    path {
      shape-rendering: geometricPrecision;
    }

    text {
        text-anchor: middle;
        dominant-baseline: middle;
        line-height: 1;
    }

    /* Layer labels */
    text.label {
        font-weight: bold;
        text-anchor: start;
        paint-order: stroke;
        fill: var(--color--layer--text);
        dominant-baseline: text-before-edge;
    }


    /* Keys */
    rect.key,
    rect.combo {
        fill: var(--color--key--bg);
        stroke: var(--color--key--border);
    }
    .tap {
        fill: var(--color--key--text--tap);
    }
    .shifted,
    .hold {
        font-size: 18px;
        text-anchor: middle;
    }
    .shifted {
        dominant-baseline: hanging;
        fill: var(--color--key--text--shifted);
    }
    .hold {
        font-size: 12px;
        dominant-baseline: ideographic;
        fill: var(--color--key--text--hold);
    }

    .keypos-32,
    .keypos-34,
    .keypos-36,
    .keypos-37 {
        --color--key--bg: var(--color--material--blue-gray--100);
        --color--key--border: var(--color--material--blue-gray--200);
    }

    /*
     * Combos
     */
    .combo {
        --color--key--bg: var(--color--combo--bg);
        --color--key--border: var(--color--combo--border);
        --color--key--text--tap: var(--color--combo--text--tap);
        --color--key--text--shifted: var(--color--combo--text--shifted);
        --color--key--text--hold: var(--color--combo--text--hold);
    }

    rect.combo {
        stroke-width: 0;
    }
    path.combo {
        stroke-width: 1;
        stroke: var(--color--combo--dendron);
        stroke-dasharray: 2, 2;
        fill: none;
    }
    .combo.tap {
        font-size: 10px;
    }
    .combo.shifted {
        font-size: 10px;
        transform: translateY(-2px);
    }
    .combo.hold {
        font-size: 10px;
        transform: translateY(4px);
    }

    /*
     * Transparent, None, and Ghost Keys
     */
    .trans,
    .none,
    .ghost {
      opacity: 0.4;
    }
    .none {
      display: none;
    }
    .trans {
        --color--key--bg: var(--color--trans--bg);
        --color--key--border: var(--color--trans--border);
        --color--key--text--tap: var(--color--trans--text--tap);
        --color--key--text--shifted: var(--color--trans--text--shifted);
        --color--key--text--hold: var(--color--trans--text--hold);
    }
    .ghost {
        --color--key--bg: var(--color--ghost--bg);
        --color--key--border: var(--color--ghost--border);
        --color--key--text--tap: var(--color--ghost--text--tap);
        --color--key--text--shifted: var(--color--ghost--text--shifted);
        --color--key--text--hold: var(--color--ghost--text--hold);
    }